ConstantWeighting:
  weight:
    # type: Gaussian
    # mean: 0.5
    # sigma: 0.1
    type: Uniform
    lower_limit: 0.15
    upper_limit: 0.85

LogisticLinearWeighting:
  scale:
    # type: Gaussian
    # mean: 1.0
    # sigma: 0.5
    type: Uniform
    lower_limit: -3.0
    upper_limit: 3.0
  offset:
    # type: Gaussian
    # mean: 0.0
    # sigma: 0.5
    type: Uniform
    lower_limit: -10.0
    upper_limit: 10.0