data_cfg:
  train_path: './data/processed_data/supercal'
  volumetric_rates_path: './data/processed_data/volumetric_rates'
  sep: ' '
model_cfg:
  only_evaluate_calibrators: True
  ratio_par_name: w
  stretch_par_name: s
  use_physical_ratio: False
  use_volumetric_rates: False
  cosmology_par_names: []
  shared_par_names: [
    alpha,
    beta,
    Rb,
    sig_Rb,
    gamma_Ebv
  ]
  independent_par_names: [
    Mb,
    c,
    sig_c,
    s,
    sig_s,
    tau_Ebv
  ]
  host_galaxy_cfg:
    use_properties: False
    covariance_null_value: 1000.
    property_names: [
      local_u-g,
      local_mass,
      local_ssfr,
      global_u-g,
      global_mass,
      global_ssfr
    ]
    init_values:
      local_u-g:
        means: [1., 1.5]
        sigmas: [.25, .1]
      local_mass:
        means: [9.5, 8.7]
        sigmas: [.25, .2]
      local_ssfr:
        means: [-11., -9.]
        sigmas: [1., 1.]
      global_u-g:
        means: [1., 1.5]
        sigmas: [.25, .1]
      global_mass:
        means: [11., 9.]
        sigmas: [1., 1.]
      global_ssfr:
        means: [-11., -9.]
        sigmas: [1., 1.]
      t:
        means: [0., 4.]
        sigmas: [3., 1.]
  preset_values:
    H0: 73.0
    Om0: 0.3
    w0: -1.
    wa: 0.
    prompt_fraction: 0.63
    eta: 0.000102
    Mb_1: -19.49
    Mb_2: -19.40
    s_1: -1.34
    s_2: 0.39
    sig_s_1: 0.69
    sig_s_2: 0.65
    c_1: -0.037
    c_2: 0.043
    sig_c_1: 0.076
    sig_c_2: 0.043
    tau_Ebv_1: 0.017
    tau_Ebv_2: 0.034
    alpha_1: -0.186
    alpha_2: -0.186
    beta_1: 3.1
    beta_2: 3.1
    Rb_1: 4.077
    Rb_2: 4.077
    sig_Rb_1: 0.970
    sig_Rb_2: 0.970
    gamma_Ebv_1: 3.282
    gamma_Ebv_2: 3.282
    w: 0.384
    sig_int_1: 0.
    sig_int_2: 0.
    shift_Rb: 0.
  prior_bounds:
    Mb:
      lower: -100.
      upper: 100.
    beta:
      lower: 1.
      upper: 5.
    s:
      lower: -100.
      upper: 100.
    sig_s:
      lower: 0.
      upper: 10.
    c:
      lower: -100.
      upper: 100.
    sig_c: 
      lower: 0.
      upper: 10.
    sig_int:
      lower: 0.
    Rb:
      lower: 1.
      upper: 10.
    sig_Rb:
      lower: 0.
      upper: 5.
    tau_Rb:
      lower: 0.
    gamma_Rb:
      lower: 1.
      upper: 20.
    shift_Rb:
      lower: 0.
    Ebv:
      lower: 0.
      upper: 10.
    tau_Ebv:
      lower: 0.
    gamma_Ebv:
      lower: 1.
      upper: 20.
    w:
      lower: 0.12
      upper: 0.88
    H0:
      lower: 50.
      upper: 90.
    Om0:
      lower: 0.01
      upper: 0.99
    w0:
      lower: -5.
      upper: 5.
    wa:
      lower: -5.
      upper: 5.
    eta:
      lower: -6.
      upper: 2.
    prompt_fraction:
      lower: 0.
      upper: 1.
  init_values:
    Mb: -19.3
    sig_c: 0.05
    sig_s: 1.
    Ebv: 0.12
    tau_Ebv: 0.02
    gamma_Ebv: 2.9
    Rb: 3.7
    tau_Rb: 0.3
    gamma_Rb: 5.5
    shift_Rb: 1.5
    Om0: 0.3
    w0: -1.
    wa: 0.
    prompt_fraction: 0.63
    eta: -3.99
  use_sigmoid: False
  sigmoid_cfg:
    scale: 750.
    shift: 0.99
  dtd_cfg:
    t0: 0.04
    t1: 0.5
  Ebv_integral_lower_bound: 0.
  Ebv_integral_upper_bound: -9999.
  Rb_integral_lower_bound: 0.
  Rb_integral_upper_bound: -9999.
  resolution_gEbv: 0.01
  cdf_limit_gEbv: 0.995
  resolution_gRb: 0.01
  cdf_limit_gRb: 0.995
emcee_cfg:
  save_path: './results'
  file_name: "chains.hdf5"
  run_name: "base"
  pool_type: "MPI"
  continue_from_chain: False
  n_walkers: 256
  n_steps: 100000
  tau_tol: 25
  default_tau: 2000
  default_burnin: 20000
clearml_cfg:
  project_name: SN_2Pop
  offline_mode: True
  tags: []
  task_type: 'training'
plot_cfg:
  n_samples: max
  label_kwargs:
    fontsize: 16
  corner_cfg:
    smooth: 1.
    hist_bin_factor: 2.
    label_kwargs:
      fontsize: 16
    hist_kwargs:
      density: True
  corner_cfg_ranges:
    gamma_Ebv:
      lower: 1.
      upper: 9.
  property_ranges:
    local_u-g:
      lower: 0.25
      upper: 2.25
    local_mass:
      lower: 6.
      upper: 11.
    local_ssfr:
      lower: -45.
      upper: -8.
    global_u-g:
      lower: 0.25
      upper: 2.
    global_mass:
      lower: 8.
      upper: 12.
    global_ssfr:
      lower: -30.
      upper: -8.5
    t:
      lower: -5.5
      upper: 10.5