data_cfg:
  path: './data/Super_0.023_0.15_zHD_cut_22_no_2007rx'
  sep: ' '
model_cfg:
  ratio_par_name: w
  shared_par_names: [
    alpha,
    beta,
    Rb,
    sig_Rb,
    gamma_Ebv
  ]
  independent_par_names: [
    Mb,
    c,
    sig_c,
    s,
    sig_s,
    tau_Ebv
  ]
  preset_values:
    H0: 73.0
    sig_int_1: 0.
    sig_int_2: 0.
  prior_bounds:
    Mb:
      lower: -100.
      upper: 100.
    beta:
      lower: 1.
      upper: 5.
    s:
      lower: -100.
      upper: 100.
    sig_s:
      lower: 0.
      #upper: 15.
    c:
      lower: -100.
      upper: 100.
    sig_c: 
      lower: 0.
      #upper: 15.
    sig_int:
      lower: 0.
    Rb:
      lower: 1.
      upper: 6.
    sig_Rb:
      lower: 0.
      upper: 1.5
    tau_Rb:
      lower: 0.
    gamma_Rb:
      lower: 1.
      upper: 10.
    tau_Ebv:
      lower: 0.
      #upper: 100.
    gamma_Ebv:
      lower: 1.
      upper: 7.
    w:
      lower: 0.12
      upper: 0.88
  init_values:
    #alpha: -0.14
    #beta: 3.1
    #Rb: 3.7
    #sig_Rb: 0.6
    #alpha_g: 2.9
    Mb: -19.3
    #c: -0.09
    sig_c: 0.05
    #s: 0.1
    sig_s: 1.
    tau_Ebv: 0.04
    tau_Rb: 0.05
    #w: 0.4
  use_sigmoid: False
  sigmoid_cfg:
    scale: 750.
    shift: 0.99
  lower_bound_Ebv: 0.
  upper_bound_Ebv: 10.
  lower_bound_Rb: 0.
  upper_bound_Rb: 10.
emcee_cfg:
  save_path: './results/baseline'
  file_name: "chains.hdf5"
  run_name: "base"
  pool_type: "MPI"
  continue_from_chain: False
  n_walkers: 128
  n_steps: 100
  tau_tol: 25
  default_tau: 2000
plot_cfg:
  smooth: 1.
  smooth1d: 1.
  label_kwargs:
    fontsize: 16