model_par_cfg:
  ratio_par_name: w
  shared_par_names: [
    alpha,
    beta,
    s,
    sig_s,
    Rb,
    sig_Rb,
    tau,
    alpha_g
  ]
  independent_par_names: [
    Mb,
    c,
    sig_c
  ]
  preset_values:
    H0: 73.0
    sig_int_1: 0.
    sig_int_2: 0.
  prior_bounds:
    beta: [1, 5]
    s: [0]
    sig_s: [0]
    sig_c: [0]
    sig_int: [0]
    Rb: [1., 6.]
    sig_Rb: [0., 1.5]
    tau: [0]
    alpha_g: [1., 7.]
    w: [0.12, 0.88]
