data_cfg:
  path: './data/Super_0.023_0.15_zHD_cut_22_no_2007rx'
  sep: ' '
model_cfg:
  ratio_par_name: w
  shared_par_names: [
    alpha,
    beta,
    Rb,
    sig_Rb,
    alpha_g
  ]
  independent_par_names: [
    Mb,
    c,
    sig_c,
    s,
    sig_s,
    tau
  ]
  preset_values:
    H0: 73.0
    sig_int_1: 0.
    sig_int_2: 0.
  prior_bounds:
    beta:
      lower: 1.
      upper: 5.
    sig_s:
      lower: 0.
    sig_c: 
      lower: 0.
    sig_int:
      lower: 0.
    Rb:
      lower: 1.
      upper: 6.
    sig_Rb:
      lower: 0.
      upper: 1.5
    tau:
      lower: 0.
    alpha_g:
      lower: 1.
      upper: 7.
    w:
      lower: 0.12
      upper: 0.88
  use_sigmoid: False
  sigmoid_cfg:
    scale: 100.
    shift: 0.9
  prior_lower_bound: 0.
  prior_upper_bound: 10.
emcee_cfg:
  save_path: './Results/baseline'
  file_name: "chains.h5"
  run_name: "base"
  n_walkers: 128
  n_steps: 100
  n_workers: 1