data_cfg:
  path: './data/Pantheon+SH0ES.dat'
  sep: ' '
prep_cfg:
  flag_duplicate_sn: True
  max_peak_date_diff: 10.
  max_angular_separation: 1.
  column_names: [
    'CID',
    'zHD',
    'mB',
    'mBERR',
    'x1',
    'x1ERR',
    'c',
    'cERR', 
    'x0',
    'COV_x1_c',
    'COV_x1_x0',
    'COV_c_x0',
    'HOST_LOGMASS',
    'HOST_LOGMASS_ERR',
    'biasCor_m_b_COVSCALE',
  ]
  new_column_names: [
    'CID',
    'z',
    'mB',
    'mBErr',
    'x1',
    'x1Err',
    'c',
    'cErr',
    'x0',
    'cov_x1_c',
    'cov_x1_x0',
    'cov_c_x0',
    'global_mass',
    'global_mass_err',
    'bias_corr_factor'
  ]

  use_bias_corrections: True
  apparent_mag_column_name: 'mB'
  apparent_mag_err_column_name: 'mBErr'
  apparent_mag_bias_correction_column_name: 'biasCor_m_b'
  apparent_mag_bias_correction_err_column_name: 'biasCorErr_m_b'

  use_redshift_cutoff: True
  redshift_cutoff: 0.01

  use_x1_cutoff: True
  x1_cutoff: 3.0

  use_color_cutoff: True
  color_cutoff: 0.3