data_cfg:
  path: './data/raw_data'
  dataset: 'supercal.fitres' #'Pantheon+SH0ES.dat'
  morphologies: 'SN-morph-type-t'
  local_properties: 'jones_2018'
  sep: ' '
prep_cfg:

  include_calibrator_sn: True

  use_host_morphologies: True
  use_jones_properties: True
  jones_properties: [
    'local_u-g',
    'local_mass',
    'local_ssfr',
    'global_u-g',
    'global_mass',
    'global_ssfr',
  ]

  flag_duplicate_sn: True
  max_peak_date_diff: 10.
  max_angular_separation: 1.
  max_redshift_separation: 0.001

  column_names: [
    'CID',
    'zHD',
    'mB',
    'mBERR',
    'x1',
    'x1ERR',
    'c',
    'cERR', 
    'x0',
    'COV_x1_c',
    'COV_x1_x0',
    'COV_c_x0',
    'HOST_LOGMASS',
    'HOST_LOGMASS_ERR',
    'biasCor_m_b_COVSCALE',
  ]
  new_column_names: [
    'CID',
    'z',
    'mB',
    'mBErr',
    'x1',
    'x1Err',
    'c',
    'cErr',
    'x0',
    'cov_x1_c',
    'cov_x1_x0',
    'cov_c_x0',
    'global_mass',
    'global_mass_err',
    'bias_corr_factor'
  ]

  use_bias_corrections: False #True
  apparent_mag_column_name: 'mB'
  apparent_mag_err_column_name: 'mBErr'
  apparent_mag_bias_correction_column_name: 'biasCor_m_b'
  apparent_mag_bias_correction_err_column_name: 'biasCorErr_m_b'

  use_redshift_cutoff: True
  redshift_lower_cutoff: 0.023
  redshift_upper_cutoff : 0.15

  use_mb_err_cutoff: True
  mb_err_cutoff: 0.2

  use_x1_cutoff: True
  x1_cutoff: 3.0

  use_x1_err_cutoff: True
  x1_err_cutoff: 1.5

  use_color_cutoff: True
  color_cutoff: 0.3
  
  use_fitprob_cutoff: True
  fitprob_cutoff: 0.001

  use_peak_date_err_cutoff: True
  peak_date_err_cutoff: 2.

  output_path: './data/'
  output_name: "test_supercal" #"Pantheon+SH0ES"
  output_sep: ' '