data_cfg:
    train_path: ./data/simulated_data/
    sep: ','
model_cfg:
    pars: [Mb,alpha,beta,sig_int,Om0,w0]
    preset_values: 
        H0: 70.
        wa: 0.
        Om0: 0.3
        w0: -1.
    init_values: 
        Mb: -19.3
        alpha: 0.128
        beta: 3.1
        sig_int: 0.12
        Om0: 0.3
        w0: -1.
        wa: 0.
    prior_bounds: 
        Mb: 
            lower: -23.
            upper: -15.
        alpha: 
            lower: -10.
            upper: 10.
        beta: 
            lower: -10.
            upper: 10.
        sig_int: 
            lower: 0.00
            upper: 10.
        Om0: 
            lower: 0.01
            upper: 0.99
        w0: 
            lower: -3.
            upper: 1.
        wa: 
            lower: -5.
            upper: 5.
emcee_cfg:
    n_walkers: 60
    n_steps: 100
    save_path: ./results/simulated_data
    extra_path: ''
    use_full_sample: True
    init_idx: 43
    n_runs: 2
    pool_type: ''
